<?php

use App\Models\SituationGeographique;
use Illuminate\Database\Seeder;

class SituationGeographiqueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sg = [
            [ 'id' => 1, 'code' => 'LAC', 'libelle' => 'AKPAKPA CENTRE', ],
[ 'id' => 2, 'code' => 'LFI', 'libelle' => 'FIDJROSSE', ],
[ 'id' => 3, 'code' => 'LGA', 'libelle' => 'GANHI', ],
[ 'id' => 4, 'code' => 'LKH', 'libelle' => 'KOUHOUNOU', ],
[ 'id' => 5, 'code' => 'LKP', 'libelle' => 'KPONDEHOU', ],
[ 'id' => 6, 'code' => 'LPK', 'libelle' => 'PK5', ],
[ 'id' => 7, 'code' => 'LSI', 'libelle' => 'SIKECODJI', ],
[ 'id' => 8, 'code' => 'LSK', 'libelle' => 'SEKANDJI', ],
[ 'id' => 9, 'code' => 'LVE', 'libelle' => 'VEDOKO', ],
[ 'id' => 10, 'code' => 'MCA', 'libelle' => 'AGOUE', ],
[ 'id' => 11, 'code' => 'MCB', 'libelle' => 'BOPA', ],
[ 'id' => 12, 'code' => 'MCG', 'libelle' => 'GRAND POPO', ],
[ 'id' => 13, 'code' => 'MCH', 'libelle' => 'HILLACONDJI', ],
[ 'id' => 14, 'code' => 'MCL', 'libelle' => 'LOBOGO', ],
[ 'id' => 15, 'code' => 'MCO', 'libelle' => 'COME', ],
[ 'id' => 16, 'code' => 'MDA', 'libelle' => 'AZOVE', ],
[ 'id' => 17, 'code' => 'MDD', 'libelle' => 'DJAKOTOMEY', ],
[ 'id' => 18, 'code' => 'MDK', 'libelle' => 'KLOUEKANMEY', ],
[ 'id' => 19, 'code' => 'MDL', 'libelle' => 'LALO', ],
[ 'id' => 20, 'code' => 'MDO', 'libelle' => 'DOGBO', ],
[ 'id' => 21, 'code' => 'MDP', 'libelle' => 'APLAHOUE', ],
[ 'id' => 22, 'code' => 'MDT', 'libelle' => 'TOVIKLIN', ],
[ 'id' => 23, 'code' => 'MLA', 'libelle' => 'ATHIEME', ],
[ 'id' => 24, 'code' => 'MLH', 'libelle' => 'HOUEYOGBE DOUTOU', ],
[ 'id' => 25, 'code' => 'MLO', 'libelle' => 'LOKOSSA', ],
[ 'id' => 26, 'code' => 'OAA', 'libelle' => 'ADJARRA', ],
[ 'id' => 27, 'code' => 'OBA', 'libelle' => 'ADJA OUERE', ],
[ 'id' => 28, 'code' => 'OBB', 'libelle' => 'BONOU', ],
[ 'id' => 29, 'code' => 'OBI', 'libelle' => 'IFANGNI', ],
[ 'id' => 30, 'code' => 'OBK', 'libelle' => 'KETOU', ],
[ 'id' => 31, 'code' => 'OBN', 'libelle' => 'IKPINLE', ],
[ 'id' => 32, 'code' => 'OBP', 'libelle' => 'POBE', ],
[ 'id' => 33, 'code' => 'OBS', 'libelle' => 'SAKETE', ],
[ 'id' => 34, 'code' => 'OMA', 'libelle' => 'MISSERETE', ],
[ 'id' => 35, 'code' => 'OPD', 'libelle' => 'DANGBO', ],
[ 'id' => 36, 'code' => 'OPG', 'libelle' => 'AGUEGUE', ],
[ 'id' => 37, 'code' => 'OPJ', 'libelle' => 'ADJOHOUN/AZOWLISSE', ],
[ 'id' => 38, 'code' => 'OPN', 'libelle' => 'PORTO NOVO', ],
[ 'id' => 39, 'code' => 'OPV', 'libelle' => 'AVRANKOU', ],
[ 'id' => 40, 'code' => 'OSD', 'libelle' => 'DJEREGBE', ],
[ 'id' => 41, 'code' => 'OSP', 'libelle' => 'SEME KPODJI', ],
[ 'id' => 42, 'code' => 'OTA', 'libelle' => 'TOKPOTA', ],
[ 'id' => 43, 'code' => 'QAC', 'libelle' => 'ABOMEY CALAVI', ],
[ 'id' => 44, 'code' => 'QAS', 'libelle' => 'SO AVA', ],
[ 'id' => 45, 'code' => 'QCO', 'libelle' => 'COCOTOMEY', ],
[ 'id' => 46, 'code' => 'QGO', 'libelle' => 'GODOMEY', ],
[ 'id' => 47, 'code' => 'QJZ', 'libelle' => 'ZOGBADJE', ],
[ 'id' => 48, 'code' => 'QLA', 'libelle' => 'ALLADA', ],
[ 'id' => 49, 'code' => 'QLF', 'libelle' => 'TOFFO SEDJI', ],
[ 'id' => 50, 'code' => 'QLN', 'libelle' => 'NIAOULI', ],
[ 'id' => 51, 'code' => 'QLO', 'libelle' => 'OUEGBO', ],
[ 'id' => 52, 'code' => 'QLS', 'libelle' => 'SEKOU', ],
[ 'id' => 53, 'code' => 'QLT', 'libelle' => 'ATTOGON', ],
[ 'id' => 54, 'code' => 'QOK', 'libelle' => 'KPOMASSE', ],
[ 'id' => 55, 'code' => 'QOP', 'libelle' => 'PAHOU', ],
[ 'id' => 56, 'code' => 'QOT', 'libelle' => 'TORI BOSSITO', ],
[ 'id' => 57, 'code' => 'QOU', 'libelle' => 'OUIDAH', ],
[ 'id' => 58, 'code' => 'QTR', 'libelle' => 'ATROKPOCODJI', ],
[ 'id' => 59, 'code' => 'QZE', 'libelle' => 'ZE', ],
[ 'id' => 60, 'code' => 'QZZ', 'libelle' => 'ZINVIE', ],
[ 'id' => 61, 'code' => 'RBA', 'libelle' => 'BANIKOARA', ],
[ 'id' => 62, 'code' => 'RBG', 'libelle' => 'GOUMORI', ],
[ 'id' => 63, 'code' => 'RBK', 'libelle' => 'KEROU', ],
[ 'id' => 64, 'code' => 'RBR', 'libelle' => 'BRIGNANMAROU', ],
[ 'id' => 65, 'code' => 'RBT', 'libelle' => 'TOURA', ],
[ 'id' => 66, 'code' => 'REI', 'libelle' => 'KPEBIE', ],
[ 'id' => 67, 'code' => 'RKA', 'libelle' => 'KANDI', ],
[ 'id' => 68, 'code' => 'RKG', 'libelle' => 'GOGONOU', ],
[ 'id' => 69, 'code' => 'RKK', 'libelle' => 'KARIMAMA', ],
[ 'id' => 70, 'code' => 'RKM', 'libelle' => 'MALANVILLE', ],
[ 'id' => 71, 'code' => 'RKS', 'libelle' => 'SEGBANA', ],
[ 'id' => 72, 'code' => 'RNB', 'libelle' => 'BEMBEREKE', ],
[ 'id' => 73, 'code' => 'RND', 'libelle' => 'N\'DALI', ],
[ 'id' => 74, 'code' => 'RNL', 'libelle' => 'KALALE', ],
[ 'id' => 75, 'code' => 'RNN', 'libelle' => 'NIKKI', ],
[ 'id' => 76, 'code' => 'RNP', 'libelle' => 'PERERE', ],
[ 'id' => 77, 'code' => 'RNS', 'libelle' => 'SINENDE', ],
[ 'id' => 78, 'code' => 'RPA', 'libelle' => 'PARAKOU', ],
[ 'id' => 79, 'code' => 'RTI', 'libelle' => 'IKEMON', ],
[ 'id' => 80, 'code' => 'RTK', 'libelle' => 'KILIBO', ],
[ 'id' => 81, 'code' => 'RTO', 'libelle' => 'OUESSE', ],
[ 'id' => 82, 'code' => 'RTP', 'libelle' => 'PAPANE', ],
[ 'id' => 83, 'code' => 'RTT', 'libelle' => 'TCHAOUROU', ],
[ 'id' => 84, 'code' => 'RTU', 'libelle' => 'TOUI', ],
[ 'id' => 85, 'code' => 'SCA', 'libelle' => 'CENTRALE AKPAKPA', ],
[ 'id' => 86, 'code' => 'SCF', 'libelle' => 'CENTRE DE FORMATION', ],
[ 'id' => 87, 'code' => 'SCS', 'libelle' => 'COMPOSANTE SANITAIRE', ],
[ 'id' => 88, 'code' => 'SET', 'libelle' => 'ETOILE ROUGE', ],
[ 'id' => 89, 'code' => 'SGL', 'libelle' => 'USINE GLODJIGBE', ],
[ 'id' => 90, 'code' => 'SHT', 'libelle' => 'POSTE HT1', ],
[ 'id' => 91, 'code' => 'SMG', 'libelle' => 'MAGASIN GODOMEY', ],
[ 'id' => 92, 'code' => 'SSG', 'libelle' => 'STATION GBEGAMEY', ],
[ 'id' => 93, 'code' => 'SSH', 'libelle' => 'TECKERAIE SEHOUE', ],
[ 'id' => 94, 'code' => 'SSI', 'libelle' => 'SIEGE', ],
[ 'id' => 95, 'code' => 'SSM', 'libelle' => 'STATION MARIA GLETTA', ],
[ 'id' => 96, 'code' => 'SSV', 'libelle' => 'STATION VEDOKO', ],
[ 'id' => 97, 'code' => 'TBA', 'libelle' => 'BASSILA', ],
[ 'id' => 98, 'code' => 'TBL', 'libelle' => 'ALEDJO', ],
[ 'id' => 99, 'code' => 'TBP', 'libelle' => 'PENOUSSOULOU', ],
[ 'id' => 100, 'code' => 'TDC', 'libelle' => 'COPARGO', ],
[ 'id' => 101, 'code' => 'TDJ', 'libelle' => 'DJOUGOU', ],
[ 'id' => 102, 'code' => 'TDO', 'libelle' => 'OUAKE', ],
[ 'id' => 103, 'code' => 'TNA', 'libelle' => 'NATITINGOU', ],
[ 'id' => 104, 'code' => 'TNF', 'libelle' => 'KOUARFA', ],
[ 'id' => 105, 'code' => 'TNK', 'libelle' => 'KOUANDE', ],
[ 'id' => 106, 'code' => 'TNP', 'libelle' => 'PEHUNCO', ],
[ 'id' => 107, 'code' => 'TNR', 'libelle' => 'KEROU', ],
[ 'id' => 108, 'code' => 'TNT', 'libelle' => 'TOUCOUTOUNA', ],
[ 'id' => 109, 'code' => 'TTA', 'libelle' => 'TANGUIETA', ],
[ 'id' => 110, 'code' => 'TTB', 'libelle' => 'BOUKOUMBE', ],
[ 'id' => 111, 'code' => 'TTC', 'libelle' => 'COBLI', ],
[ 'id' => 112, 'code' => 'TTM', 'libelle' => 'MATERI', ],
[ 'id' => 113, 'code' => 'TTP', 'libelle' => 'PORGA', ],
[ 'id' => 114, 'code' => 'ZAB', 'libelle' => 'ABOMEY', ],
[ 'id' => 115, 'code' => 'ZBC', 'libelle' => 'COVE', ],
[ 'id' => 116, 'code' => 'ZBD', 'libelle' => 'ZAGNANADO', ],
[ 'id' => 117, 'code' => 'ZBG', 'libelle' => 'AGBANGNIZOUN', ],
[ 'id' => 118, 'code' => 'ZBJ', 'libelle' => 'DJIDJA', ],
[ 'id' => 119, 'code' => 'ZBK', 'libelle' => 'ZAKPOTA TINDJI', ],
[ 'id' => 120, 'code' => 'ZBN', 'libelle' => 'CANA', ],
[ 'id' => 121, 'code' => 'ZBO', 'libelle' => 'BOHICON', ],
[ 'id' => 122, 'code' => 'ZBU', 'libelle' => 'OUINHI', ],
[ 'id' => 123, 'code' => 'ZBZ', 'libelle' => 'ZOGBODOMEY', ],
[ 'id' => 124, 'code' => 'ZDB', 'libelle' => 'BANTE', ],
[ 'id' => 125, 'code' => 'ZDG', 'libelle' => 'GLAZOUE', ],
[ 'id' => 126, 'code' => 'ZDP', 'libelle' => 'PAOUINGNAN', ],
[ 'id' => 127, 'code' => 'ZDS', 'libelle' => 'SAVALOU', ],
[ 'id' => 128, 'code' => 'ZDV', 'libelle' => 'SAVE', ],
[ 'id' => 129, 'code' => 'ZDZ', 'libelle' => 'DASSA ZOUME', ],

        ];
        SituationGeographique::insert($sg);
    }
}
