<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Imports\MatriculeDirectionHoraireImport;
use App\Jobs\TestJob;
use App\Models\Horaire;
use App\Models\Team;
use App\Models\User;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;


class TestController extends Controller
{
    // public function test()
    // {
    //     // $data = $this->csv_to_array('PERSONNEL.csv');

    //     // foreach ($data as $d){
    //     //     list($nom, $prenom, $matricule, $username, $direction, $position) = explode(";", $d["nom;pren;mat;username;dir;position"]);
    //     //     $real_username = str_replace('@sbee.bj','',$username);
    //     //     try {
    //     //         $user = User::create([
    //     //             'nom' => utf8_encode($nom),
    //     //             'prenom' => utf8_encode($prenom),
    //     //             'username' => str_replace('@mhi.ca','',$real_username),
    //     //             'email' => $username,
    //     //             'password' => '',
    //     //             'matricule' => $matricule,
    //     //             'direction_id' => $direction,
    //     //             'situation_geographique_id' => $position,
    //     //         ]);
    //     //         $user->roles()->sync([3]);

    //     //     } catch (\Illuminate\Database\QueryException $th) {
    //     //         dump($d["nom;pren;mat;username;dir;position"]);
    //     //     }
    //     // }

    //     dd('test import users ok');
    // }

    public function import()
    {

        $liste = [
            ['matricule' => 836, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 6068, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7530, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7766, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3738, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 3644, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3735, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3739, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3515, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 555, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7579, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 2488, 'direction' => 'SG', 'horaires' => ['08H-17H']],
            ['matricule' => 4705, 'direction' => 'CESS', 'horaires' => ['08H-17H']],
            ['matricule' => 7418, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7196, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3070, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 4747, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 4141, 'direction' => 'CCMP', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7649, 'direction' => 'CCRP', 'horaires' => ['08H-17H']],
            ['matricule' => 3714, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 6073, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3247, 'direction' => 'SG', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4411, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4682, 'direction' => 'DSI', 'horaires' => ['08H-17H']],
            ['matricule' => 3742, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 3063, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 6077, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 6077, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 2422, 'direction' => 'DSI', 'horaires' => ['07H-16H']],
            ['matricule' => 3676, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 6440, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7524, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 472, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 4003, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7763, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3624, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 871, 'direction' => 'GOUVERNANCE', 'horaires' => ['07H-16H']],
            ['matricule' => 3792, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 3643, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7621, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7698, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3723, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 579, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4598, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3072, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7550, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 7630, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 6562, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4347, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 7608, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 441, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4711, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 686, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4195, 'direction' => 'DSI', 'horaires' => ['07H30-16H30']],
            ['matricule' => 441, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3715, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 6079, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 5365, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3147, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7794, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 2373, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7540, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7438, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7100, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 7019, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3291, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3594, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4276, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 7556, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 2450, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3293, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 2443, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 4578, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 6570, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3986, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 2468, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4357, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3505, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4798, 'direction' => 'DSI', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7098, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7701, 'direction' => 'DSI', 'horaires' => ['07H-16H']],
            ['matricule' => 7708, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3467, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 6560, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 5092, 'direction' => 'SG', 'horaires' => ['08H-17H']],
            ['matricule' => 4343, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4573, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3251, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4611, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 2441, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 4169, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 7667, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7525, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 3031, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4575, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7699, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3987, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 4829, 'direction' => 'DSI', 'horaires' => ['08H-17H']],
            ['matricule' => 7414, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 6504, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 783, 'direction' => 'GOUVERNANCE', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7091, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 7706, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 7759, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 12, 'direction' => 'CCRP', 'horaires' => ['08H-17H']],
            ['matricule' => 4572, 'direction' => 'DPAS', 'horaires' => ['']],
            ['matricule' => 7207, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 445, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7030, 'direction' => 'SG', 'horaires' => ['08H-17H']],
            ['matricule' => 3665, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7831, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 6563, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 4477, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 3484, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4947, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7074, 'direction' => 'SG', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4085, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7101, 'direction' => 'DRH', 'horaires' => ['07H-16H']],
            ['matricule' => 7564, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4662, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3905, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 3618, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7085, 'direction' => 'GOUVERNANCE', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3485, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 2, 'direction' => 'DCC', 'horaires' => ['']],
            ['matricule' => 3586, 'direction' => 'DCC', 'horaires' => ['']],
            ['matricule' => 7013, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3300, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7529, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4406, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3717, 'direction' => 'DJ', 'horaires' => ['08H-17H']],
            ['matricule' => 7412, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7084, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 3083, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4470, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 4174, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4020, 'direction' => 'DCC', 'horaires' => ['07H-16H']],
            ['matricule' => 4402, 'direction' => 'DSI', 'horaires' => ['08H-17H']],
            ['matricule' => 3498, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3729, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 7, 'direction' => 'DPAS', 'horaires' => ['']],
            ['matricule' => 4510, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 5005, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3255, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 4375, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 4375, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 4375, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 4281, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7654, 'direction' => 'DSI', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3302, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3099, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7675, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3692, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 949, 'direction' => 'GOUVERNANCE', 'horaires' => ['08H-17H']],
            ['matricule' => 7198, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 6564, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 4708, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 3051, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 4576, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3901, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7659, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3667, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3777, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 3075, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3451, 'direction' => 'GOUVERNANCE', 'horaires' => ['08H-17H']],
            ['matricule' => 3579, 'direction' => 'DJ', 'horaires' => ['07H-16H']],
            ['matricule' => 6561, 'direction' => 'DJ', 'horaires' => ['']],
            ['matricule' => 3304, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 7682, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7083, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7695, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 4309, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 482, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 7522, 'direction' => 'CESS', 'horaires' => ['08H-17H']],
            ['matricule' => 4297, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 989, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4501, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3259, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 3059, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 5305, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 6443, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 1969, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7359, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 2138, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3546, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 3448, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 464, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7671, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7551, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7664, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 7637, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3076, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7527, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7767, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7076, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 7076, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 7076, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 7801, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3346, 'direction' => 'DJ', 'horaires' => ['08H-17H']],
            ['matricule' => 6567, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 6, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 5412, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 7563, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 835, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3418, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3308, 'direction' => 'DCC', 'horaires' => ['07H-16H']],
            ['matricule' => 7428, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3719, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 3091, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7528, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 3453, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 4755, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 3457, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3101, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4595, 'direction' => 'SG', 'horaires' => ['07H-16H']],
            ['matricule' => 4416, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7697, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3481, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7668, 'direction' => 'CCRP', 'horaires' => ['08H-17H']],
            ['matricule' => 3894, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3537, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 3707, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 4137, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 716, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3030, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7001, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 4381, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4652, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 3617, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3084, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 9, 'direction' => 'DSI', 'horaires' => ['08H-17H']],
            ['matricule' => 7077, 'direction' => 'SG', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7777, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 980, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4168, 'direction' => 'DSI', 'horaires' => ['07H-16H']],
            ['matricule' => 3544, 'direction' => 'DJ', 'horaires' => ['07H-16H']],
            ['matricule' => 4352, 'direction' => 'DSI', 'horaires' => ['08H-17H']],
            ['matricule' => 4774, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 4458, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 7640, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7700, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 1211, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 7568, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 6072, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3130, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3470, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3946, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 4317, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4021, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7012, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3265, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 3656, 'direction' => 'CCMP', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3369, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3904, 'direction' => 'CCRP', 'horaires' => ['08H-17H']],
            ['matricule' => 3096, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3312, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3097, 'direction' => 'DJ', 'horaires' => ['08H-17H']],
            ['matricule' => 7416, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3516, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 7793, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 4086, 'direction' => 'GOUVERNANCE', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4643, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 7311, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 6070, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 2481, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 912, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 7655, 'direction' => 'DSI', 'horaires' => ['07H-16H']],
            ['matricule' => 4637, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7099, 'direction' => 'CCRP', 'horaires' => ['08H-17H']],
            ['matricule' => 4334, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 3092, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3510, 'direction' => 'CCMP', 'horaires' => ['07H30-16H30']],
            ['matricule' => 2414, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 3108, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 4660, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4848, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7569, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3836, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7673, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 931, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3514, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 7674, 'direction' => 'DPAS', 'horaires' => ['']],
            ['matricule' => 5015, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 1117, 'direction' => 'SG', 'horaires' => ['08H-17H']],
            ['matricule' => 7177, 'direction' => 'CESS', 'horaires' => ['08H-17H']],
            ['matricule' => 6089, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3437, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 4353, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3068, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3208, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3438, 'direction' => 'DCC', 'horaires' => ['07H-16H']],
            ['matricule' => 3675, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 830, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3625, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7669, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7711, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 5600, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7696, 'direction' => 'DJ', 'horaires' => ['08H-17H']],
            ['matricule' => 5599, 'direction' => 'SG', 'horaires' => ['']],
            ['matricule' => 2487, 'direction' => 'CCMP', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4485, 'direction' => 'GOUVERNANCE', 'horaires' => ['08H-17H']],
            ['matricule' => 4376, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 6568, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3975, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 4070, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3463, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7031, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7736, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 960, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 3480, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4267, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7780, 'direction' => 'DSI', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3103, 'direction' => 'DJ', 'horaires' => ['07H30-16H30']],
            ['matricule' => 5591, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3641, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4639, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 4639, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 4639, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 3963, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 862, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 838, 'direction' => 'CESS', 'horaires' => ['07H-16H']],
            ['matricule' => 3404, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 2354, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4555, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7775, 'direction' => 'DSI', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4619, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4265, 'direction' => 'DAF', 'horaires' => ['07H-16H']],
            ['matricule' => 6075, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 5568, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7041, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 4401, 'direction' => 'DCC', 'horaires' => ['07H-16H']],
            ['matricule' => 7081, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7748, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 454, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 7075, 'direction' => 'GOUVERNANCE', 'horaires' => ['08H-17H']],
            ['matricule' => 6018, 'direction' => 'CCMP', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3818, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 3271, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 4263, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7653, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 4635, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 7740, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3087, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 474, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 458, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 4502, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 4, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 4124, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 460, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 4069, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 3612, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 7562, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7092, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3659, 'direction' => 'CESS', 'horaires' => ['08H-17H']],
            ['matricule' => 3472, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 4424, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7761, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 7735, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 7178, 'direction' => 'CESS', 'horaires' => ['']],
            ['matricule' => 4205, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3961, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 3683, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3969, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 6007, 'direction' => 'DSI', 'horaires' => ['08H-17H']],
            ['matricule' => 7011, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4472, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 4472, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 4472, 'direction' => 'CSE', 'horaires' => ['08H-17H']],
            ['matricule' => 7029, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 6000, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 1964, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 4670, 'direction' => 'DSI', 'horaires' => ['08H-17H']],
            ['matricule' => 4389, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7101, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 3662, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7006, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7107, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 7005, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7369, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 7802, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3352, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 3314, 'direction' => 'SG', 'horaires' => ['08H-17H']],
            ['matricule' => 3061, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 3273, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 5, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7651, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 2433, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 4022, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 3093, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 537, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 737, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 995, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 7028, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3023, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7018, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 6001, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 3839, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 1662, 'direction' => 'DPAS', 'horaires' => ['']],
            ['matricule' => 10, 'direction' => 'DPAS', 'horaires' => ['']],
            ['matricule' => 4720, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 6012, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 4683, 'direction' => 'DSI', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4155, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 7713, 'direction' => 'SG', 'horaires' => ['08H-17H']],
            ['matricule' => 3652, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 4607, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 5999, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 3899, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3244, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7739, 'direction' => 'CESS', 'horaires' => ['08H-17H']],
            ['matricule' => 6008, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7008, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4644, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 3628, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 3195, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4370, 'direction' => 'DRH', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3090, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 3509, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3958, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3067, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7650, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 6446, 'direction' => 'DPAS', 'horaires' => ['']],
            ['matricule' => 6071, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 6062, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4367, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 4275, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 2478, 'direction' => 'DAI', 'horaires' => ['08H-17H']],
            ['matricule' => 3542, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 829, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 4498, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 6009, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3660, 'direction' => 'CCMP', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3635, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 7003, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3115, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3277, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 7792, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3044, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 3131, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 4125, 'direction' => 'DPAS', 'horaires' => ['07H30-16H30']],
            ['matricule' => 628, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7769, 'direction' => 'DPAS', 'horaires' => ['']],
            ['matricule' => 7097, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3095, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 7413, 'direction' => 'DAF', 'horaires' => ['08H-17H']],
            ['matricule' => 11, 'direction' => 'DAF', 'horaires' => ['']],
            ['matricule' => 3746, 'direction' => 'CCMP', 'horaires' => ['07H30-16H30']],
            ['matricule' => 7520, 'direction' => 'PRMP', 'horaires' => ['08H-17H']],
            ['matricule' => 3279, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 6046, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3146, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4319, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 7023, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 7023, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 7609, 'direction' => 'DSI', 'horaires' => ['07H-16H']],
            ['matricule' => 4663, 'direction' => 'DD', 'horaires' => ['08H-17H']],
            ['matricule' => 7565, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3021, 'direction' => 'DRH', 'horaires' => ['08H-17H']],
            ['matricule' => 7515, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3474, 'direction' => 'DSI', 'horaires' => ['08H-17H']],
            ['matricule' => 7786, 'direction' => 'DAF', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3475, 'direction' => 'DJ', 'horaires' => ['07H30-16H30']],
            ['matricule' => 3685, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 3106, 'direction' => 'SG', 'horaires' => ['07H30-16H30']],
            ['matricule' => 489, 'direction' => 'SG', 'horaires' => ['08H-17H']],
            ['matricule' => 3102, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 4713, 'direction' => 'DPAS', 'horaires' => ['07H-16H']],
            ['matricule' => 4408, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
            ['matricule' => 4497, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 3520, 'direction' => 'DPMEER', 'horaires' => ['08H-17H']],
            ['matricule' => 8, 'direction' => 'DEPP', 'horaires' => ['08H-17H']],
            ['matricule' => 7209, 'direction' => 'DPAS', 'horaires' => ['08H-17H']],
            ['matricule' => 3709, 'direction' => 'DEC', 'horaires' => ['08H-17H']],
            ['matricule' => 3581, 'direction' => 'DAF', 'horaires' => ['07H-16H']],
            ['matricule' => 7714, 'direction' => 'SG', 'horaires' => ['08H-17H']],
            ['matricule' => 7417, 'direction' => 'DJ', 'horaires' => ['07H30-16H30']],
            ['matricule' => 4609, 'direction' => 'DCC', 'horaires' => ['08H-17H']],
        ];
        $errors = [];
        $de = [];

        foreach ($liste as $key => $l) {
            $direction = Team::firstOrNew(['name' => $l['direction']]);
            $direction->save();
            if ($direction->id) {
                $user = User::where('matricule', $l['matricule'])->first();
                if ($user) {
                    $user->team_id = $direction->id;
                    $user->save();
                    foreach ($l['horaires'] as $h) {
                        $horaire = Horaire::where('name', $h)->first();
                        if ($horaire)
                            $user->horaires()->attach($horaire);
                    }
                } else {
                    array_push($errors, $l['matricule']);
                }
            } else {
                array_push($de, $l['direction']);
            }
        }

        dd($errors, $de);
    }

    public function csv_to_array($filename = '', $delimiter = ',')
    {
        if (!file_exists($filename) || !is_readable($filename))
            return FALSE;

        $header = NULL;
        $data = array();
        if (($handle = fopen($filename, 'r')) !== FALSE) {
            while (($row = fgetcsv($handle, 1000, $delimiter)) !== FALSE) {
                if (!$header)
                    $header = $row;
                else
                    $data[] = array_combine($header, $row);
            }
            fclose($handle);
        }
        return $data;
    }

    public function job()
    {
        TestJob::dispatch();
    }
}
